[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
<<<<<<< HEAD
=======
    "exa-py>=1.14.20",
>>>>>>> 715dfa8 (Feature: Deep Search | Web Search)
    "httpx>=0.28.1",
]
